###
GET http://localhost:4000/api/employees

###
POST http://localhost:4000/api/employees
Content-Type: application/json

{
    "name" : "Perroni",
    "position": "Java Delevoper",
    "office": "Maringá",
    "salary" : "5.500"

    
}

###
GET http://localhost:4000/api/employees/611ce9705645c34714c29b2f

###
DELETE http://localhost:4000/api/employees/611ce9705645c34714c29b2f

###
PUT http://localhost:4000/api/employees/611ce9705645c34714c29b2f
Content-Type: application/json

{
    "name" : "Marcelo",
    "position": "Java Delevoper",
    "office": "Maringá",
    "salary" : "8000"

    
}